CREATE USER edu IDENTIFIED BY edu12 ACCOUNT UNLOCK
DEFAULT TABLESPACE USERS;

GRANT RESOURCE, CONNECT
TO edu;


DROP TABLE MEMBERS;

CREATE TABLE MEMBERS(
    MNO NUMBER NOT NULL
,   EMAIL VARCHAR2(40) NOT NULL
,   PWD VARCHAR2(100) NOT NULL
,   MNAME VARCHAR2(50) NOT NULL
,   CRE_DATE DATE NOT NULL
,   MOD_DATE NOT NULL
);

COMMENT ON TABLE MEMBERS IS '회원기본정보';

COMMENT ON TABLE MEMBERS.MNO IS '123';


ALTER TABLE MEMBERS
ADD CONSTRAINT MEMBERS_MNO_PK PRIMARY KEY(MNO);

ALTER TABLE MEMBERS
ADD CONSTRAINT MEMBERS_EMAIL_UK UNIQUE(EMAIL);

CREATE SEQUENCE MEMBERS_MNO_SEQ
INCREMENT BY 1
START WITH 1;

INSERT INTO MEMBERS
(MNO, EMAIL, PWD, MNAME, CRE_DATE, MOD_DATE)
VALUES (MEMBERS_MNO_SEQ.NEXTVAL, 's1@TEST.COM', '1111',
       '홍길동', SYSDATE, SYSDATE);

INSERT INTO MEMBERS
(MNO, EMAIL, PWD, MNAME, CRE_DATE, MOD_DATE)
VALUES (MEMBERS_MNO_SEQ.NEXTVAL, 's2@TEST.COM', '1111',
       '일지매', SYSDATE, SYSDATE);
       
INSERT INTO MEMBERS
(MNO, EMAIL, PWD, MNAME, CRE_DATE, MOD_DATE)
VALUES (MEMBERS_MNO_SEQ.NEXTVAL, 's3@TEST.COM', '1111',
       '이몽룡', SYSDATE, SYSDATE);
INSERT INTO MEMBERS
(MNO, EMAIL, PWD, MNAME, CRE_DATE, MOD_DATE)
VALUES (MEMBERS_MNO_SEQ.NEXTVAL, 's4@TEST.COM', '1111',
       '성충향', SYSDATE, SYSDATE);
       
INSERT INTO MEMBERS
(MNO, EMAIL, PWD, MNAME, CRE_DATE, MOD_DATE)
VALUES (MEMBERS_MNO_SEQ.NEXTVAL, 's5@TEST.COM', '1111',
       '임꺽정', SYSDATE, SYSDATE);
       

SELECT *
FROM members;


