INSERT INTO CLASS_CATEGORY (CATEGORY_NO, CATEGORY_NAME)
VALUES (SEQ_CLASS_CATEGORY_NO.NEXTVAL, '레져/스포츠');

INSERT INTO CLASS_CATEGORY
VALUE(CATEGORY_NO, CATEGORY_NAME)
VALUES(SEQ_CLASS_CATEGORY_NO.NEXTVAL, '뷰티');

INSERT INTO CLASS_CATEGORY
VALUE(CATEGORY_NO, CATEGORY_NAME)
VALUES(SEQ_CLASS_CATEGORY_NO.NEXTVAL, '자기계발');

INSERT INTO CLASS_CATEGORY
VALUE(CATEGORY_NO, CATEGORY_NAME)
VALUES(SEQ_CLASS_CATEGORY_NO.NEXTVAL, '핸드메이드');

INSERT INTO CLASS_CATEGORY
VALUE(CATEGORY_NO, CATEGORY_NAME)
VALUES(SEQ_CLASS_CATEGORY_NO.NEXTVAL, '쿠킹');

SELECT *
FROM class_category;

COMMIT;	