INSERT INTO BOARD_CATEGORY (CATEGORY_NO , CATEGORY_NAME)
VALUES (1, '공지사항');  
INSERT INTO BOARD_CATEGORY (CATEGORY_NO , CATEGORY_NAME)
VALUES (2, '자유');  
INSERT INTO BOARD_CATEGORY (CATEGORY_NO , CATEGORY_NAME)
VALUES (3, '정보');  


INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '공지사항1', 1, SYSDATE, SYSDATE, '공지사항 내용1입니다.', 1);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '공지사항2', 1, SYSDATE, SYSDATE, '공지사항 내용2입니다.', 1);


INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '공지사항3', 1, SYSDATE, SYSDATE, '공지사항 내용2입니다.', 1);


INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '자유게시글1', 2, SYSDATE, SYSDATE, '이것은 자유게시판 게시글입니다.', 2);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '정보게시글1', 3, SYSDATE, SYSDATE, '이 글은 정보 게시글입니다.', 3);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '자유게시글2', 2, SYSDATE, SYSDATE, '자유게시판의 두 번째 글입니다.', 2);  



                 
 INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '자유게시판', 1, SYSDATE, SYSDATE, '공지사항 내용1입니다.', 2);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '자유게시판2', 1, SYSDATE, SYSDATE, '공지사항 내용2입니다.', 2);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '자유게시글1', 2, SYSDATE, SYSDATE, '이것은 자유게시판 게시글입니다.', 2);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '정보게시글1', 3, SYSDATE, SYSDATE, '이 글은 정보 게시글입니다.', 3);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '자유게시글2', 2, SYSDATE, SYSDATE, '자유게시판의 두 번째 글입니다.', 2);  


INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '자유게시판', 1, SYSDATE, SYSDATE, '공지사항 내용1입니다.', 3);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '자유게시판', 1, SYSDATE, SYSDATE, '공지사항 내용2입니다.', 2);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '자유게시글1', 2, SYSDATE, SYSDATE, '이것은 자유게시판 게시글입니다.', 3);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '정보게시글1', 3, SYSDATE, SYSDATE, '이 글은 정보 게시글입니다.', 3);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '자유게시글2', 2, SYSDATE, SYSDATE, '자유게시판의 두 번째 글입니다.', 2);  


INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '자유게시판', 1, SYSDATE, SYSDATE, '공지사항 내용2입니다.', 2);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '자유게시글1', 2, SYSDATE, SYSDATE, '이것은 자유게시판 게시글입니다.', 3);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '정보게시글1', 3, SYSDATE, SYSDATE, '이 글은 정보 게시글입니다.', 3);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '자유게시글2', 2, SYSDATE, SYSDATE, '자유게시판의 두 번째 글입니다.', 2);  

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '자유게시판', 1, SYSDATE, SYSDATE, '공지사항 내용2입니다.', 2);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '자유게시글1', 2, SYSDATE, SYSDATE, '이것은 자유게시판 게시글입니다.', 3);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '정보게시글1', 3, SYSDATE, SYSDATE, '이 글은 정보 게시글입니다.', 3);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '자유게시글2', 2, SYSDATE, SYSDATE, '자유게시판의 두 번째 글입니다.', 2);  


COMMIT;
//NOTE 더미데이터 //