

commit;


INSERT INTO BOARD_CATEGORY (CATEGORY_NO , CATEGORY_NAME)
VALUES (1, '공지사항');  
INSERT INTO BOARD_CATEGORY (CATEGORY_NO , CATEGORY_NAME)
VALUES (2, '자유');  
INSERT INTO BOARD_CATEGORY (CATEGORY_NO , CATEGORY_NAME)
VALUES (3, '정보');  

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '3월6일 공지사항', 1, SYSDATE, SYSDATE, '3월6일 공지사항 내용1입니다.', 1);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '3월7일 공지사항', 1, SYSDATE, SYSDATE, '3월7일 공지사항 내용2입니다.', 1);


INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '3월8일 공지사항', 1, SYSDATE, SYSDATE, '3월8일 공지사항 내용입니다.', 1);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '3월9일 공지사항', 1, SYSDATE, SYSDATE, '3월9일 공지사항 내용2입니다.', 1);


INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '3월10일 공지사항', 1, SYSDATE, SYSDATE, '3월10일 공지사항 내용1입니다.', 1);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '3월11일 공지사항', 1, SYSDATE, SYSDATE, '3월11일 공지사항 내용2입니다.', 1);


INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '3월12일 공지사항', 1, SYSDATE, SYSDATE, '3월12일 공지사항 내용1입니다.', 1);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '3월13일 공지사항', 1, SYSDATE, SYSDATE, '3월13일 공지사항 내용2입니다.', 1);



INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '3월14일 공지사항', 1, SYSDATE, SYSDATE, '3월14일공지사항 내용1입니다.', 1);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '3월15일 공지사항', 1, SYSDATE, SYSDATE, '3월15일공지사항 내용2입니다.', 1);


INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '3월16일 공지사항', 1, SYSDATE, SYSDATE, '3월16일공지사항 내용2입니다.', 1);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '3월17일 공지사항', 1, SYSDATE, SYSDATE, '3월17일공지사항 내용1입니다.', 1);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '3월18일 공지사항', 1, SYSDATE, SYSDATE, '3월18일공지사항 내용2입니다.', 1);


INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '3월19일 공지사항', 1, SYSDATE, SYSDATE, '3월19일공지사항 내용2입니다.', 1);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '3월20일 공지사항', 1, SYSDATE, SYSDATE, '3월20일공지사항 내용1입니다.', 1);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '3월21일 공지사항', 1, SYSDATE, SYSDATE, '3월21일공지사항 내용2입니다.', 1);


INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '드리블원데이클래스 있음?', 2, SYSDATE, SYSDATE, '풋살을 좋아하고 잘하고 싶어하는 사람인데 능력치를 육각형으로 비교하면 다른 건 개인연습을 통해 키우는게 가능한데 드리블은 다른영역인 것 같더라 혼자 볼마스터리는 잘 해내는 편인데 사람세워두고(실전) 플레이는 어려운것같아 
드리블 능력을 키우고 싶은데 드리블위주 수업이나 원데이클래스가 있을까?
 ', 2);


INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '서울에 요리 원데이클래스 들을만한 곳 있어?', 3, SYSDATE, SYSDATE, '검색하면 다 코요아야...여기가 좋나 그래두?', 2);  
                
 INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '3월 15일 뷰티쪽 배울사람?', 4, SYSDATE, SYSDATE, '인스타 보니까 서울경기 지역 20대30대 댄스동호회 있던데 같이 배워볼사람 있나?', 2);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '나중에 도자기 클래스 해봐야지', 6, SYSDATE, SYSDATE, '잼서보임ㅋ.', 2);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '오늘 원데이 클래스로 화분 만들고 왔다 ㅋㅋㅋ', 2, SYSDATE, SYSDATE, '재밌었어!!!!!', 2);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '클래스도 많아지고 자급자족이 유행인가봐', 8, SYSDATE, SYSDATE, '메이크업 원데이 클래스도 많이 열리고 요즘은 의상 클래스까지 생겼더라 장터 리젠도 안되는데 불경기에도 이 취미 유지하는 사람들은 자급자족으로 옮겨가나', 2);  




INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '와인 마스터 클래스, 소믈리에 클래스', 8, SYSDATE, SYSDATE, '관심 있으신 분들은 댓글달아주세요.', 3);


INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '커피믹스 전용 머그잔', 3, SYSDATE, SYSDATE, '원데이 클래스가서 만들어옴', 3);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '요새 원데이클래스 관심있어서 찾아보는데', 9, SYSDATE, SYSDATE, '재미있어 보이는게 없는데?...', 2);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '난 낼부터 원데이클래스 간다 ㅇㅇ', 10, SYSDATE, SYSDATE, '매달1.2회 내가 배우고 싶은거 배워야지 돈이 좀 비싼데 1대1이라 그런듯;;', 3);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '난 목욜부터 원데이클래스 나감', 11, SYSDATE, SYSDATE, '나를 채우는 해가 됐음한다', 2);  


INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '사진 원데이 클래스 같은거 도움되나요?', 5, SYSDATE, SYSDATE, '평소에 피규어사진만 찍어서 인물사진은 잘 못찍어요.. 이번에 부모님좀 찍어드리고 싶어서 이것저것 알아보는중에 원데이 클래스를 발견해서 들어볼까 좀 고민중인데 어떨까요', 2);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '가죽스트랩 원데이클래스 어떤거같음', 14, SYSDATE, SYSDATE, '이런느낌으로 만들 수 있다고 하는데 8만원짜리 클래스임 레인저 줄이 마음에 안들어서 하나 만들어보고싶은데 내 손으로 직접 만들면 뜻깊겠지?', 3);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '원데이클래스 할꺼없나 하루만 배우는거', 15, SYSDATE, SYSDATE, '휴가가 기니깐 딴짓하고싶어짐', 2);  

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '원데이클래스라도 많이다녀서 혼자놀아야겟다 싶었는데', 6, SYSDATE, SYSDATE, '왜이리 할게 없냐', 2);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '나도 가발 잘 만들어보고싶은데 학원다녀야할까?', 8, SYSDATE, SYSDATE, '추천좀', 3);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '원데이 클래스 같은 건 어떻게 정보를 찾나요?', 4, SYSDATE, SYSDATE, '원데이 클래스로 커피를 배우는 걸 접해보고 싶은데요 어디서 검색을 해서 찾는건가요?', 3);


INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '유영 훈련도 못받는거야?', 9, SYSDATE, SYSDATE, '원데이 클래스 등록해서 훈련하면 안되는거임?.', 2);  

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '향수 만드는 원데이 클래스 하고싶음', 19, SYSDATE, SYSDATE, '남친이가 생기면... 데이트할때 가야지...', 2); 


INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '좋은 원데이클래스 있어서 추천한다', 20, SYSDATE, SYSDATE, '드리블좀 배워보고 싶어서 찾던중에 고마운사람이 추천해줘서 나도 공유한다 




제목은 아라원데이클래스고 드리블좋아하거나 팁을 얻고 싶은 사람들 오거라 



일단 난 신청했어', 3);



INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '원데이클래스라도 많이다녀서 혼자놀아야겟다 싶었는데', 6, SYSDATE, SYSDATE, '왜이리 할게 없냐', 2);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '나도 가발 잘 만들어보고싶은데 학원다녀야할까?', 8, SYSDATE, SYSDATE, '추천좀', 3);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '원데이 클래스 같은 건 어떻게 정보를 찾나요?', 4, SYSDATE, SYSDATE, '원데이 클래스로 커피를 배우는 걸 접해보고 싶은데요 어디서 검색을 해서 찾는건가요?', 3);


INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '유영 훈련도 못받는거야?', 9, SYSDATE, SYSDATE, '원데이 클래스 등록해서 훈련하면 안되는거임?.', 2);  

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '향수 만드는 원데이 클래스 하고싶음', 19, SYSDATE, SYSDATE, '남친이가 생기면... 데이트할때 가야지...', 2); 


INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '원데이클래스라도 많이다녀서 혼자놀아야겟다 싶었는데', 6, SYSDATE, SYSDATE, '왜이리 할게 없냐', 2);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '나도 가발 잘 만들어보고싶은데 학원다녀야할까?', 8, SYSDATE, SYSDATE, '추천좀', 3);

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '원데이 클래스 같은 건 어떻게 정보를 찾나요?', 4, SYSDATE, SYSDATE, '원데이 클래스로 커피를 배우는 걸 접해보고 싶은데요 어디서 검색을 해서 찾는건가요?', 3);


INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '유영 훈련도 못받는거야?', 9, SYSDATE, SYSDATE, '원데이 클래스 등록해서 훈련하면 안되는거임?.', 2);  

INSERT INTO NOTE (NOTE_NO, NOTE_TITLE, MEMBER_NO, CREATE_AT, MODIFY_AT, NOTE_CONTENT, CATEGORY_NO)
VALUES (SEQ_NOTE_NO.NEXTVAL, '향수 만드는 원데이 클래스 하고싶음', 19, SYSDATE, SYSDATE, '남친이가 생기면... 데이트할때 가야지...', 2); 






COMMIT;
//NOTE 더미데이터 //
