DROP TABLE MEMBER;
DROP SEQUENCE MEMBER_SEQ;

CREATE TABLE MEMBER (
	MEMBER_NO NUMBER(5)	NOT NULL PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(100) NOT NULL,
	MEMBER_PWD VARCHAR2(100) NOT NULL,
	MEMBER_NAME VARCHAR2(100) NOT NULL,
	RRN VARCHAR2(100) NOT NULL,
	TEL VARCHAR2(100) NOT NULL,
	PRIV VARCHAR2(30) NOT NULL
);

ALTER TABLE MEMBER MODIFY (PRIV DEFAULT 'user');

--RRN number(13) NOT NULL COMMENT 'resident registration number' 주민등록번호
--priv는 (privilege 권한), 약어

desc MEMBER;

CREATE SEQUENCE MEMBER_SEQ
INCREMENT BY 1
START WITH 1;
--MEMBER_NO의 고유 인덱스

INSERT INTO MEMBER
VALUE(MEMBER_NO, MEMBER_EMAIL, MEMBER_PWD, MEMBER_NAME, RRN, TEL, PRIV)
VALUES(MEMBER_SEQ.NEXTVAL, 'ctube@gmail.com', '1234', '클튜브', '000101-3000000', '010-0000-0000', 'admin');

COMMIT;

