-- MEMBER 테이블 시퀀스 삭제
DROP SEQUENCE SEQ_MEMBER_NO;

-- MEMBER 테이블 시퀀스
CREATE SEQUENCE SEQ_MEMBER_NO
START WITH 1
INCREMENT BY 1;

-- MEMBER_REPORT 테이블 시퀀스 삭제
DROP SEQUENCE SEQ_MEMBER_REPORT_NO;

-- MEMBER_REPORT 테이블 시퀀스
CREATE SEQUENCE SEQ_MEMBER_REPORT_NO
START WITH 1
INCREMENT BY 1;

-- CLASS_CATEGORY 테이블 시퀀스 삭제
DROP SEQUENCE SEQ_CLASS_CATEGORY_NO;

-- CLASS_CATEGORY 테이블 시퀀스
CREATE SEQUENCE SEQ_CLASS_CATEGORY_NO
START WITH 1
INCREMENT BY 1;

-- ODCLASS 테이블 시퀀스 삭제
DROP SEQUENCE SEQ_CLASS_NO;

-- ODCLASS 테이블 시퀀스
CREATE SEQUENCE SEQ_CLASS_NO
START WITH 1
INCREMENT BY 1;

-- BOARD_CATEGORY 테이블 시퀀스 삭제
DROP SEQUENCE SEQ_BOARD_CATEGORY_NO;

-- BOARD_CATEGORY 테이블 시퀀스
CREATE SEQUENCE SEQ_BOARD_CATEGORY_NO
START WITH 1
INCREMENT BY 1;

-- NOTE 테이블 시퀀스 삭제
DROP SEQUENCE SEQ_NOTE_NO;

-- NOTE 테이블 시퀀스
CREATE SEQUENCE SEQ_NOTE_NO
START WITH 1
INCREMENT BY 1;

-- COMMENT 테이블 시퀀스 삭제
DROP SEQUENCE SEQ_COMMENT_NO;

-- COMMENT 테이블 시퀀스
CREATE SEQUENCE SEQ_COMMENT_NO
START WITH 1
INCREMENT BY 1;

-- REPORT 테이블 시퀀스 삭제
DROP SEQUENCE SEQ_REPORT_NO;

-- REPORT 테이블 시퀀스
CREATE SEQUENCE SEQ_REPORT_NO
START WITH 1
INCREMENT BY 1;